language: java
jdk:
  - oraclejdk7

deploy:
  provider: releases
  api_key: $GITAPI
  file: "target/PortableFTPServer.jar"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report    